//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.12 at 12:44:03 AM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://user.soap.xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xml.soap.user;
