spring.application.name=AnunciosLocService
server.port=8081
server.address=192.168.1.167
#==============================
#= DATA SOURCE
#==============================
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/anunciosloc
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true