//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.20 at 12:36:53 PM WAT 
//


package xml.soap.anuncio;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.soap.anuncio package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.soap.anuncio
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddAnuncioRequest }
     * 
     */
    public AddAnuncioRequest createAddAnuncioRequest() {
        return new AddAnuncioRequest();
    }

    /**
     * Create an instance of {@link GetAnuncioRequest }
     * 
     */
    public GetAnuncioRequest createGetAnuncioRequest() {
        return new GetAnuncioRequest();
    }

    /**
     * Create an instance of {@link DeleteAnuncioRequest }
     * 
     */
    public DeleteAnuncioRequest createDeleteAnuncioRequest() {
        return new DeleteAnuncioRequest();
    }

    /**
     * Create an instance of {@link AllAnunciosProximosRequest }
     * 
     */
    public AllAnunciosProximosRequest createAllAnunciosProximosRequest() {
        return new AllAnunciosProximosRequest();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link AddAnuncioRequest.Body }
     * 
     */
    public AddAnuncioRequest.Body createAddAnuncioRequestBody() {
        return new AddAnuncioRequest.Body();
    }

    /**
     * Create an instance of {@link AddAnuncioResponse }
     * 
     */
    public AddAnuncioResponse createAddAnuncioResponse() {
        return new AddAnuncioResponse();
    }

    /**
     * Create an instance of {@link GetAnuncioRequest.Body }
     * 
     */
    public GetAnuncioRequest.Body createGetAnuncioRequestBody() {
        return new GetAnuncioRequest.Body();
    }

    /**
     * Create an instance of {@link GetAnuncioResponse }
     * 
     */
    public GetAnuncioResponse createGetAnuncioResponse() {
        return new GetAnuncioResponse();
    }

    /**
     * Create an instance of {@link DeleteAnuncioRequest.Body }
     * 
     */
    public DeleteAnuncioRequest.Body createDeleteAnuncioRequestBody() {
        return new DeleteAnuncioRequest.Body();
    }

    /**
     * Create an instance of {@link DeleteAnuncioResponse }
     * 
     */
    public DeleteAnuncioResponse createDeleteAnuncioResponse() {
        return new DeleteAnuncioResponse();
    }

    /**
     * Create an instance of {@link AllAnunciosRequest }
     * 
     */
    public AllAnunciosRequest createAllAnunciosRequest() {
        return new AllAnunciosRequest();
    }

    /**
     * Create an instance of {@link AllAnunciosProximosRequest.Body }
     * 
     */
    public AllAnunciosProximosRequest.Body createAllAnunciosProximosRequestBody() {
        return new AllAnunciosProximosRequest.Body();
    }

    /**
     * Create an instance of {@link ListAnuncioResponse }
     * 
     */
    public ListAnuncioResponse createListAnuncioResponse() {
        return new ListAnuncioResponse();
    }

    /**
     * Create an instance of {@link AnuncioType }
     * 
     */
    public AnuncioType createAnuncioType() {
        return new AnuncioType();
    }

}
