//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.20 at 12:36:53 PM WAT 
//


package xml.soap.infra;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.soap.infra package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.soap.infra
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetInfraDetailsRequest }
     * 
     */
    public GetInfraDetailsRequest createGetInfraDetailsRequest() {
        return new GetInfraDetailsRequest();
    }

    /**
     * Create an instance of {@link AllInfraMoreProximeRequest }
     * 
     */
    public AllInfraMoreProximeRequest createAllInfraMoreProximeRequest() {
        return new AllInfraMoreProximeRequest();
    }

    /**
     * Create an instance of {@link TestInfraRequest }
     * 
     */
    public TestInfraRequest createTestInfraRequest() {
        return new TestInfraRequest();
    }

    /**
     * Create an instance of {@link AddInfraRequest }
     * 
     */
    public AddInfraRequest createAddInfraRequest() {
        return new AddInfraRequest();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link GetInfraDetailsRequest.Body }
     * 
     */
    public GetInfraDetailsRequest.Body createGetInfraDetailsRequestBody() {
        return new GetInfraDetailsRequest.Body();
    }

    /**
     * Create an instance of {@link InfraResponse }
     * 
     */
    public InfraResponse createInfraResponse() {
        return new InfraResponse();
    }

    /**
     * Create an instance of {@link GetInfraDetailsResponse }
     * 
     */
    public GetInfraDetailsResponse createGetInfraDetailsResponse() {
        return new GetInfraDetailsResponse();
    }

    /**
     * Create an instance of {@link AllInfraRequest }
     * 
     */
    public AllInfraRequest createAllInfraRequest() {
        return new AllInfraRequest();
    }

    /**
     * Create an instance of {@link AllInfraMoreProximeRequest.Body }
     * 
     */
    public AllInfraMoreProximeRequest.Body createAllInfraMoreProximeRequestBody() {
        return new AllInfraMoreProximeRequest.Body();
    }

    /**
     * Create an instance of {@link AllInfraResponse }
     * 
     */
    public AllInfraResponse createAllInfraResponse() {
        return new AllInfraResponse();
    }

    /**
     * Create an instance of {@link InfraType }
     * 
     */
    public InfraType createInfraType() {
        return new InfraType();
    }

    /**
     * Create an instance of {@link TestInfraRequest.Body }
     * 
     */
    public TestInfraRequest.Body createTestInfraRequestBody() {
        return new TestInfraRequest.Body();
    }

    /**
     * Create an instance of {@link TestInfraResponse }
     * 
     */
    public TestInfraResponse createTestInfraResponse() {
        return new TestInfraResponse();
    }

    /**
     * Create an instance of {@link GeoLocationType }
     * 
     */
    public GeoLocationType createGeoLocationType() {
        return new GeoLocationType();
    }

}
